### ISSUE TITLE
The function "SDL_PIXELFLAG" has incorrect name

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#130]
https://github.com/PascalGameDevelopment/SDL2-for-Pascal/blob/3feb4767eddce88219098f76d638890d069be671/units/sdl2.pas#L356-L359

This macro-function should be named `SDL_PIXELFORMAT`, since it is used to return the pixel format, one of the `SDL_PIXELFORMAT_*` values. Am I right?

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Hi there,

thanks for the hint, but the naming is correct. This is how this macro is named in the original project headers.
