### ISSUE TITLE
sdlkeycode.inc: SDLK_QUOTE = TSDL_KeyCode('\'); is wrong.

### ISSUE THREAD

**Issue by Chixpy** [PascalGameDevelopment/SDL2-for-Pascal#136]
Hi. It's a simple mistake.

In line 37 of [sdlkeycode.inc](https://github.com/PascalGameDevelopment/SDL2-for-Pascal/blob/c094a6036d3508d2bb8a5263e689714f42831d92/units/sdlkeycode.inc#L37)

`SDLK_QUOTE = TSDL_KeyCode('\');`

must be

`SDLK_QUOTE = TSDL_KeyCode('''');`

Backslash `\` key is defined in line 67: `SDLK_BACKSLASH = TSDL_KeyCode('\');`

Actually, [SDLK_QUOTE was renamed three week ago to SDLK_APOSTROPHE, but I'think that it's for SDL3](https://github.com/libsdl-org/SDL/commit/94cbaaabbfa360419221ff3cacab4eb902f7c8a3)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Never noticed this, thanks!

Can you craft a quick patch/PR or should I do it?

Best regards

**Comment by Chixpy** [comment]
Done #137

**Comment by suve** [comment]
Oh oops. Thanks for noticing and thanks for the PR.
