### ISSUE TITLE
Calling convention modifier missing

### ISSUE THREAD

**Issue by olatov** [PascalGameDevelopment/SDL2-for-Pascal#141]
Hello,

I've noticed that some function declarations (namely, [those managing the framerate](https://github.com/PascalGameDevelopment/SDL2-for-Pascal/blob/87c9f858be97b5fe6bef5e8e1be04ef29bf6a02c/units/sdl2_gfx.pas#L110-L123) in `sdl2_gfx.pas`), are missing the `cdecl` calling convention modifier - I wonder if there's a reason for that?

I'm having troubles using these with FPC on MacOS (error linking) and Windows (Access Violation in runtime) - unless I add `cdecl` or apply `{$CALLING cdecl}` unit-wise.

Thanks.

**Comment by suve** [comment]
Yeah, this is definitely a mistake on our part. I'll try to take a better look at `sdl2_gfx.pas` later today. You can also open a PR yourself.

**Comment by olatov** [comment]
Ok cool, I'll create a PR shortly.
