### ISSUE TITLE
SDL_LockTexture problem

### ISSUE THREAD

**Issue by MKGilby** [PascalGameDevelopment/SDL2-for-Pascal#145]
Hello folks!

I have a problem using SDL_LockTexture. 

If I try to use it as it is declared in sdlrenderer.inc, it generates an Access Violation:

```
function SDL_LockTexture(texture: PSDL_Texture; const rect: PSDL_Rect; pixels: PPointer; pitch: pcint): cint; cdecl;
     external SDL_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_SDL_LockTexture' {$ENDIF} {$ENDIF};

```

But If I change the declaration to the following (and change call parameters accordingly), it works flawlessly:
```
function SDL_LockTexture(texture: PSDL_Texture; const rect: PSDL_Rect; out pixels: Pointer; out pitch: cint): cint; cdecl;
     external SDL_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_SDL_LockTexture' {$ENDIF} {$ENDIF};

```

Am I doing something wrong?

Attached a simple Lazarus test project. [SimpleStreamingTextureTest.zip](https://github.com/user-attachments/files/16740102/SimpleStreamingTextureTest.zip)

Thanks,  Gilby

**Comment by MKGilby** [comment]
I got the solution, need a new(p) and a new(pitch) before updatetexture (and disposes too, and one more ^ after p in move).

**Comment by suve** [comment]
Yes, the pointers passed to `SDL_LockTexture` need to point to valid memory. So you need to either create pointer vars and call new/dispose, or you can create non-pointer vars and pass their addresses using the `@` operator.
