### ISSUE TITLE
Should we use unit ctypes for FPC?

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [PascalGameDevelopment/SDL2-for-Pascal#26]
I wonder,

in [sdlstd.inc](https://github.com/PascalGameDevelopment/SDL2-for-Pascal/blob/master/sdlstdinc.inc) we define all the types used in SDL2. We lead them back to basic Pascal types. In this example we lead UInt16 back to Word.

```
PUInt16 = ^UInt16;
UInt16 = Word;
```

I suggest to have a conditional type conversion bound to the ctypes unit for Free Pascal.

```
{$IFDEF FPC}
  UInt16 = cuint16;
{$ELSE}
  UInt16 = Word;
{$ENDIF}
```

 The advantage is that type sizes should be chosen even more reliably for different platforms (at least in case of FPC).

**Comment by suve** [comment]
I was thinking about this myself, recently - and I think it's a good idea, since the whole idea behind the `ctypes` unit is that it should free us of having to maintain a `pascal type <-> C type` mapping ourselves. If Delphi doesn't have an analogous unit, then yes, we should hide this behind an `{$IFDEF}`.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
> 
> 
> the whole idea behind the `ctypes` unit is that it should free us of having to maintain a `pascal type <-> C type` mapping ourselves. If Delphi doesn't have an analogous unit, then yes, we should hide this behind an `{$IFDEF}`.

Exactly!

About Delphi, I'm not sure if there is something similar, but in a quick research I couldn't find anything. To make sure not to break Delphi-compatibility, It can be done as described.
