### ISSUE TITLE
SDL_JoystickHasLED function has invalid parameters count

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#42]
The function `SDL_JoystickHasLED` has the following declaration in the `sdljoystick.inc` file, in line `479`:

```pascal
function SDL_JoystickHasLED(joystick: PSDL_Joystick; button: cint32): TSDL_Bool; cdecl;
  external SDL_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_SDL_JoystickHasLED' {$ENDIF} {$ENDIF};
```
This function should have only one parameter — the joystick handle, `button` is not needed to determine if the joystick has LED or not. This import is inconsistent with the **[documentation](https://wiki.libsdl.org/SDL_JoystickHasLED)**, in which the following declaration is given:

```cpp
SDL_bool SDL_JoystickHasLED(SDL_Joystick *joystick);
```

**Comment by suve** [comment]
Solved by PR #43.
