### ISSUE TITLE
SDL_RenderGeometry

### ISSUE THREAD

**Issue by codz01** [PascalGameDevelopment/SDL2-for-Pascal#47]
Hi
i just download sdl2-for-pascal and notice that SDL_RenderGeometry is missing , do you plan to add this function ?

**Comment by suve** [comment]
The geometry API is relatively recent, having been introduced in SDL 2.0.18. I'll look into this.

**Comment by suve** [comment]
Solved by d4aac17296c2ce9564c406d392185e77f7199e42.
