### ISSUE TITLE
TODO: Implement Functions "SDL_JoystickPath" and "SDL_JoystickPathForIndex" (as of release of SDL 2.24.0)

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#51]
The following functions are not implemented:

- **[SDL_JoystickPath](https://wiki.libsdl.org/SDL_JoystickPath)**
- **[SDL_JoystickPathForIndex](https://wiki.libsdl.org/SDL_JoystickPathForIndex)**

These functions are available since SDL 2.24.0

**Comment by suve** [comment]
SDL 2.24.0 hasn't even been released yet, so you'd need to compile the library from source to use these functions, either way.

I'd prefer to wait until 2.24.0 is released, in case the API changes.

**Comment by furious-programming** [comment]
I don't need to use these functions. Just for the purposes of my own project, I checked what the library offers in terms of joysticks and found those functions for which there are no imports. I have added an issue so as not to forget about these functions in the future when a new version of SDL is released.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Just changed the title to keep this in mind. 

Thanks!

**Comment by suve** [comment]
Fixed by PR #75.
