### ISSUE TITLE
TODO: add missing "preciseX" and "preciseY" fields to the "TSDL_MouseWheelEvent" structure

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#69]
As of version 2.0.18, the [`SDL_MouseWheelEvent`](https://wiki.libsdl.org/SDL_MouseWheelEvent) structure contains two additional fields — `preciseX` and `preciseY` of type `float`. These fields are missing from the `TSDL_MouseWheelEvent` declaration.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Fixed by PR #72. Closed.
