### ISSUE TITLE
TODO: add missing "SDL_GetMemoryFunctions" procedure (SDL 2.0.7)

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#71]
In the **SDL 2.0.7**, the function [`SDL_GetMemoryFunctions`](https://wiki.libsdl.org/SDL_GetMemoryFunctions) was introduced. There is a lack of import of it. It would be good to add not only the import of this function, but also type declarations of templates of the functions to which the `SDL_GetMemoryFunctions` returns pointers. Something like:

```pascal
type
  TSDL_MallocFunc = function(size: csize_t): pointer; cdecl;
```

**Comment by suve** [comment]
Leaving this comment to let anyone interested know I'm currently looking into updating `sdlstdinc.inc`, so we don't end up duplicating work.
