### ISSUE TITLE
Video mode window minimization loops endlessly

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#8]
Run window in exclusive video mode, e.g. in 800x600 resolution:

```pascal
SDL_SetWindowSize(Window, 800, 600);
SDL_SetWindowFullScreen(Window, SDL_WINDOW_FULLSCREEN);
```
Everything is working fine. Now, press the `Alt+Tab` combination — the program window will be minimized, the resolution will be automatically changed to the original (desktop) resolution, then SDL falls into an endless minimize and restore loop. It will try to minimize the window, restore resolution, restore video mode, minimize it again, and so on. The effect is that the screen flickers rapidly and only closing the program stops this process.

The temporary solution is to disable automatic window minimalization when the window loses focus:

```pascal
SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, '0');
```
I don't know if this hint exists because of this looping problem, at least the fact that it does exist indicates a bug. This problem occurs at least on Windows 10, on different computers, so it's not my laptop's fault.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Could you provide some runnable test code, please?

**Comment by furious-programming** [comment]
And the same here — even if the problem is real, it is not due to the bindings code.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for keeping an eye on these older issues and closing them as they turned out to be not relevant anymore. Also applies for issue #9 and issue #10.
