### ISSUE TITLE
TODO: missing "display" field in the "TSDL_Event" and the "TSDL_DisplayEvent" structure.

### ISSUE THREAD

**Issue by furious-programming** [PascalGameDevelopment/SDL2-for-Pascal#81]
Some time ago the [`SDL_DisplayEvent`](https://wiki.libsdl.org/SDL_DisplayEvent) was introduced, but there is no `display` field in the `TSDL_Event` structure that would allow the data to be read for this event. What is interesting, the `SDL_DISPLAYEVENT` and other enums are added to the `sdlevents.inc` file, but there is no support for them.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks

**Comment by suve** [comment]
Fixed by PR #95.
